### ISSUE TITLE
Proton not patched automatically, manual patch works

### ISSUE THREAD

**Issue by catt0** [geefr/beatsaber-linux-goodies#33]
I went through the installation details in https://github.com/geefr/beatsaber-linux-goodies/blob/master/QBeat/README.md (including switching to Proton BeatSaber), but mods were not working. I then went through (same Beat Saber + Proton install) the steps in https://github.com/beat-saber-modding-group/BeatSaber-IPA-Reloaded/issues/18#issuecomment-526913292 and I now have fully working mods. Tested with custom avatar + saber in practice mode, so seems to be working fine.

From the doc and scripts I expected that the patches would be automatically applied, but the _alt version of the dll and so was not created. Also I had to switch from "winhttp"="native,builtin" to "winhttp"="native" in the user.reg.

System: Arch Linux; uname -a: Linux catdesktop 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux
Compiled QBeat myself from aa389720263ced14de626d2476272d65a0db3da4

Is this a known problem or do you need some further info/debugging?

P.S. Thanks for QBeat and especially the docs!

**Comment by geefr** [comment]
That's interesting, could be caused by #26. Think if that one's hit it says success but actually doesn't do anything..

If you ran a 'make install' then everything should be fine, running from within the build tree perhaps not. 

Several folks are using Arch/manjaro, so the binaries on the release page may just work for you. Alternatively check the readme in the scripts directory, qbeat just wraps those in a (slightly) nicer interface.

I'd need these for debugging:
- an 'ls -l' on the folder you ran qbeat from
- the output of './QBeat --config get' - maybe the base proton path has something weird in it

**Comment by catt0** [comment]
Just tested the prebuilt binaries and they work, but running cmake was the faster way to find out I needed qt5-quickcontrols.

I did not run make install, but I noticed that the scripts were missing, so I copied them to the build directory to make it look like the downloaded zip.

`catt0@catdesktop ..saber-linux-goodies-master/QBeat/build % ls -l
total 400
-rw-r--r-- 1 catt0 catt0  13158 Nov 24 15:55 CMakeCache.txt
drwxr-xr-x 6 catt0 catt0   4096 Nov 24 15:55 CMakeFiles
-rw-r--r-- 1 catt0 catt0  13981 Nov 24 15:55 Makefile
-rwxr-xr-x 1 catt0 catt0 343440 Nov 24 15:55 QBeat
drwxr-xr-x 5 catt0 catt0   4096 Nov 24 15:55 QBeat_autogen
-rw-r--r-- 1 catt0 catt0   1802 Nov 24 15:58 README.md
-rwxr-xr-x 1 catt0 catt0   2528 Nov 24 15:58 bs-linux-is-wine-valid.sh
-rwxr-xr-x 1 catt0 catt0   5560 Nov 24 15:58 bs-linux-modfix.sh
-rwxr-xr-x 1 catt0 catt0   2835 Nov 24 15:58 bs-linux-setup-wine.sh
-rw-r--r-- 1 catt0 catt0   3153 Nov 24 15:55 cmake_install.cmake
`
`catt0@catdesktop ..saber-linux-goodies-master/QBeat/build % ./QBeat --config get
bsInstall : /home/catt0/steamapps/common/Beat Saber
bsProtonDir : /home/catt0/steamapps/common/Proton 4.11
gameType : steam
gameVersion : 1.5.0
winePrefix : /home/catt0/.winemods
`

The winePrefix is a 32bit prefix and contains dotnet472 installed via winetricks.

**Comment by geefr** [comment]
Hm, that's odd. Everything there looks correct, and it's not the script permissions issue..

My scripts actually install .net 4.6.1 but as long as there's some version of .net installed they won't complain (--validate-wine /might/ complain but that won't stop --patch from running)

Think the outcome here is if you can reproduce this with some sequence of actions then great, otherwise lets leave this open and see if anyone else has the same issue.

(I fully expect to get a few of these issues, while I love the Linux world there's loads of scope for weird corner cases here)
