### ISSUE TITLE
Version list reported by beatmods API doesn't contain newest game version

### ISSUE THREAD

**Issue by steffenWi** [geefr/beatsaber-linux-goodies#78]
The list of versions as reported by https://beatmods.com/api/v1/version does not contain the newest version of Beatsaber, 1.13.2. This results in Beataroni not offering that version which then results in outdated versions of the modifications being downloaded and in the end BeatSaber can't start songs, at least in my case.

Question would be if it is actually neccessary to use that API call? 
Wouldn't it also be possible to just call https://beatmods.com/api/v1/mod and then get the available versions from there? That way you don't have to rely on the version list being updated by beatmods.

**Comment by ominitay** [comment]
Since this an issue with the API, it should be reported [here](https://github.com/bsmg/BeatMods-Website). I would hazard a guess that most other managers would also be affected (since basically every manager I know of checks versions against the api).

As for the second point, I don't believe that a version list could be reliably retrieved from https://beatmods.com/api/v1/mod, but feel free to prove me wrong! 

The BeatMods API is an unreliable mess, and is truly awful to work with...

**Comment by ominitay** [comment]
I just found out about this in the BeatMods codebase: https://versions.beatmods.com/versions.json
That's right. BeatMods provides the same data in two different places, and manages to make them differ. Will be filing an issue rn.
See: https://github.com/bsmg/BeatMods-Website/issues/48

**Comment by geefr** [comment]
I wouldn't be surprised if beatmods allows mods to be uploaded before the version is published to beatmods clients. May go along with the 'approved' status of mods.

(Ignoring any advanced/hacks mode I might implement at some point) Beataroni will follow ModAssistant's as the reference implementation, so while this would be possible it's not something I'd want.

**Comment by ominitay** [comment]
Has been fixed anyway

**Comment by ominitay** [comment]
BeatMods is just a complete mess and doesn't get reliably updated, all we can do is wait for v2
