### ISSUE TITLE
"Continue" button remains grayed out in Beataroni

### ISSUE THREAD

**Issue by podiki** [geefr/beatsaber-linux-goodies#83]
Would love to try out this tool (wine, dotnet, etc. is always a mess), but unfortunately Beataroni doesn't let me press the Continue button no matter what I type in the Beat Saber Installation box or what version I select. Running latest Beat Saber through Steam, on up to date Arch system (using Xmonad if the lack of window decorations matters?). Is there a config file I can write manually or something I can pass to Beataroni when I run it to bypass this problem at least?

**Comment by podiki** [comment]
Whoops, never mind, looks like I made a typo (I tried many times, wasn't able to paste into the box so that's what I get)!

Edit: for any others, I had to make sure I used the absolute path (no `~/` but `/home/...`)

**Comment by geefr** [comment]
Nice, I like easy bugs :)

Handling '~' would be useful, surprised .net doesn't just take care of it, but I guess it's implemented as part of the shell rather than supported in the Linux kernel/filesystem level?

(Alternatively I should implement a file/browse dialog at some point, or it might even be possible to hook the steam runtime and interrogate the library automatically...)

**Comment by podiki** [comment]
Nothing like creating a GitHub issue to figure it out 3 seconds later (I swear I tried that exact input before, of course).

Not sure where ~ comes into play, or know anything about .NET, sorry. Might be useful to pre-populate with the default location though? I'm guess that should cover the vast majority of Steam Beat Saber installs. Or only ask if it is not detected at default location.

(And thanks for the tool, works great! Sure beats the epic struggle that is dotnet on Wine!)
