### ISSUE TITLE
Feature Request: CLI for Beataroni

### ISSUE THREAD

**Issue by mtfurlan** [geefr/beatsaber-linux-goodies#87]
I would really like a CLI interface to beataroni like qbeat had.
I really appreciate the updates from qbeat of not having to muck about with .net in some wineprefix just to install mods, but I preferred being able to write down what commands to run instead of having to write down what to copy/click on in a gui in order to reinstall/update mods after an update.

Thanks for all the work to make beat saber modding fairly easy.

**Comment by ominitay** [comment]
In the meantime, you could try my ShellSaber project :) Just make sure to uninstall the your mods before using it if you do.

**Comment by geefr** [comment]
I'm afraid I won't be implementing this one. Fully understand the request, but beataroni is UI-only on purpose, mainly to focus on the one use case and reduce maintenance-burnout ;)

But yeah as mentioned you can use ShellSaber, and I highly recommend it (on principle, I rarely even play these days). Happy to help out with any design/debugging issues around the whole mod install approach.

Alternatively if <someone> wanted to use Beataroni's codebase for a command line tool it would probably be quite easy to do. The install utility functions should be re-useable, and if I wrote it in my usual style the core workflow/logic should be fairly independent of the UI itself. Downside there is you'll need to know C#/.net core due to the change in language.
